version: "3"
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ~/mysql/data/:/var/lib/mysql
  spring-boot-jpa-docker-webapp:
    container_name: student-api
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ~/logs:/logs
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydb
      - DATABASE_PORT=3306