spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
spring.jpa.show-sql: true
logging:
  file: /logs/student-enrolment.log
  level:
    com.b1.studentenrolment: INFO
    org.hibernate: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
