name: student-api-ci-cd

on:
  push:
    branches: [ master ]
  paths:
    - 'src/**'
    - 'terraform/ecs-task-definition-services/**'

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Unit tests, Integration Tests and build artifact
      run: mvn clean install -Pintegration

    - name: Create & Push App Docker image
      run: |
        APP_TAG=`git rev-parse --short HEAD`
        echo $APP_TAG
        docker build -t abirdatta/b1-test-api:$APP_TAG .
        docker login -u abirdatta -p ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}
        docker push abirdatta/b1-test-api:$APP_TAG

    - name: rolling-update-ecs-service
      working-directory: terraform/ecs-task-definition-services
      run: |
        APP_TAG=`git rev-parse --short HEAD`
        sed -i -e "s/SED_IMAGE_VERSION/$APP_TAG/g" *.tf
        terraform workspace new dev
        terraform workspace select dev
        terraform init
        terraform plan
        terraform apply --auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-1
