name: student-api-ci-cd

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ xyz ]
  pull_request:
    branches: [ master ]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Code
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run Unit tests, Integration Tests and build artifact
      run: mvn clean install -Pintegration

    # Runs a set of commands using the runners shell
    - name: Create & Push App Docker image
      run: |
        APP_TAG=`git rev-parse --short HEAD`
        echo $APP_TAG
        docker build -t abirdatta/b1-test-api:$APP_TAG .
        docker login -u abirdatta -p ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}
        docker push abirdatta/b1-test-api:$APP_TAG
  deploy:
    runs-on: [ubuntu-latest]
    needs: test-build-push
    steps:
      - name: rolling-update-ecs-service
        working-directory: terraform/ecs-task-definition-services
        run: |
          APP_TAG=`git rev-parse --short HEAD`
          sed -i -e "s/SED_IMAGE_VERSION/APP_TAG/g" *.tf; \
          terraform init
          terraform workspace new dev
          terraform plan
          terraform apply --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_DEFAULT_REGION: ap-southeast-1
