name: student-api-infra-deploy

on:
  push:
    branches: [ master ]
    tags:
      - INFRA-DEPLOY-*
    paths:
      - 'terraform/infra/**'
      - 'terraform/db/**'

jobs:
  create-aws-infra:
    runs-on: [ubuntu-latest]
    steps:
      - name: Get the latest terraform version
        run: make terraform-install
      - name: create-aws-network-instance-cluster-infra
        working-directory: terraform/infra
        run: make terraform-apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_DEFAULT_REGION: ap-southeast-1
      - name: create-aws-db-infra
        working-directory: terraform/db
        run: make terraform-apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_DEFAULT_REGION: ap-southeast-1
