name: student-api-infra-deploy

on:
  push:
    branches: [ master ]
    tags:
      - INFRA-DEPLOY-*
    paths:
      - 'terraform/infra/**'
      - 'terraform/db/**'

jobs:
  create-aws-infra:
    runs-on: [ubuntu-latest]
    env:
      TF_WORKSPACE: dev
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: 'Terraform Init Infra'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform/infra'
          tf_actions_comment: true
      - name: 'Terraform Plan Infra'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'terraform/infra'
          tf_actions_comment: true
      - name: 'Terraform Apply Infra'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: 'terraform/infra'
          tf_actions_comment: true
      - name: 'Terraform Init DB'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform/db'
          tf_actions_comment: true
      - name: 'Terraform Plan DB'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'terraform/db'
          tf_actions_comment: true
      - name: 'Terraform Apply DB'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: 'terraform/db'
          tf_actions_comment: true

