name: student-api-infra-deploy

on:
  push:
    branches: [ xyz ]
    paths:
      - 'terraform/infra/**'

jobs:
  create-aws-infra:
    runs-on: [ubuntu-latest]
    steps:
      - name: create-aws-network-instance-cluster-infra
        working-directory: terraform/infra
        run: |
          terraform init
          terraform workspace new dev
          terraform plan
          terraform apply --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_DEFAULT_REGION: ap-southeast-1
      - name: create-aws-db-infra
        working-directory: terraform/db
        run: |
          terraform init
          terraform workspace new dev
          terraform plan
          terraform apply --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_DEFAULT_REGION: ap-southeast-1
