name: student-api-infra-deploy

on:
  push:
    branches: [ master ]
    tags:
      - INFRA-DEPLOY-*
    paths:
      - 'terraform/infra/**'
      - 'terraform/db/**'

jobs:
  create-aws-infra:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v1
      - name: create-aws-network-instance-cluster-infra
        working-directory: terraform/infra
        run: |
          /usr/bin/terraform workspace new dev
          /usr/bin/terraform workspace select dev
          /usr/bin/terraform init -input=false
          /usr/bin/terraform plan -input=false
          /usr/bin/terraform apply -input=false -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_DEFAULT_REGION: ap-southeast-1
      - name: create-aws-db-infra
        working-directory: terraform/db
        run: |
          /usr/bin/terraform workspace new dev
          /usr/bin/terraform workspace select dev
          /usr/bin/terraform init -input=false
          /usr/bin/terraform plan -input=false
          /usr/bin/terraform apply -input=false -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_DEFAULT_REGION: ap-southeast-1
