name: student-api-infra-deploy

on:
  push:
    branches: [ master ]
    tags:
      - INFRA-DEPLOY-*
    paths:
      - 'terraform/infra/**'
      - 'terraform/db/**'

jobs:
  create-aws-infra:
    runs-on: [ubuntu-latest]
    steps:
      - name: 'Terraform Init Infra'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform/infra'
          tf_actions_comment: true
        env:
          TF_WORKSPACE: dev
      - name: 'Terraform Plan Infra'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'terraform/infra'
          tf_actions_comment: true
        env:
          TF_WORKSPACE: dev
      - name: 'Terraform Apply Infra'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.12.13
            tf_actions_subcommand: 'apply'
            tf_actions_working_dir: 'terraform/infra'
            tf_actions_comment: true
          env:
            TF_WORKSPACE: dev
      - name: 'Terraform Init DB'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform/db'
          tf_actions_comment: true
        env:
          TF_WORKSPACE: dev
      - name: 'Terraform Plan DB'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'terraform/db'
          tf_actions_comment: true
        env:
          TF_WORKSPACE: dev
      - name: 'Terraform Apply DB'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.12.13
            tf_actions_subcommand: 'apply'
            tf_actions_working_dir: 'terraform/db'
            tf_actions_comment: true
          env:
            TF_WORKSPACE: dev

